bugtracker/config/routes.rb
Bugtracker::Application.routes.draw do
  get "search/do_search"

  resources :comments


  resources :ticket_statuses


  devise_for :users
  resources :tickets do
    resources :comments
  end
  resources :ticket_statuses
  resources  :projects do
    resources :tickets
  end
  resources :users

  root :to => "home#index"
  match '/token' => 'home#token', :as => :token
   
  match '/admin', :to =>'admin#index'
  match '/search', :to =>'search#index'
end

bugtracker/app/controllers/ticket_statuses_controller.rb
class TicketStatusesController < ApplicationController
  # GET /ticket_statuses
  # GET /ticket_statuses.json
  def index
    @ticket_statuses = TicketStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ticket_statuses }
    end
  end

  # GET /ticket_statuses/1
  # GET /ticket_statuses/1.json
  def show
    @ticket_status = TicketStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket_status }
    end
  end

  # GET /ticket_statuses/new
  # GET /ticket_statuses/new.json
  def new
    @ticket_status = TicketStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket_status }
    end
  end

  # GET /ticket_statuses/1/edit
  def edit
    @ticket_status = TicketStatus.find(params[:id])
  end

  # POST /ticket_statuses
  # POST /ticket_statuses.json
  def create
    @ticket_status = TicketStatus.new(params[:ticket_status])

    respond_to do |format|
      if @ticket_status.save
        format.html { redirect_to @ticket_status, notice: 'Ticket status was successfully created.' }
        format.json { render json: @ticket_status, status: :created, location: @ticket_status }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ticket_statuses/1
  # PUT /ticket_statuses/1.json
  def update
    @ticket_status = TicketStatus.find(params[:id])

    respond_to do |format|
      if @ticket_status.update_attributes(params[:ticket_status])
        format.html { redirect_to @ticket_status, notice: 'Ticket status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_statuses/1
  # DELETE /ticket_statuses/1.json
  def destroy
    @ticket_status = TicketStatus.find(params[:id])
    @ticket_status.destroy

    respond_to do |format|
      format.html { redirect_to ticket_statuses_url }
      format.json { head :no_content }
    end
  end
end

bugtracker/app/helpers/ticket_statuses_helper.rb
module TicketStatusesHelper
end

bugtracker/app/views/ticket_statuses/_form.html.erb
<%= form_for(@ticket_status) do |f| %>
  <% if @ticket_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_status.errors.count, "error") %> prohibited this ticket_status from being saved:</h2>

      <ul>
      <% @ticket_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bugtracker/app/views/ticket_statuses/edit.html.erb
<h1>Editing ticket_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_status %> |
<%= link_to 'Back', ticket_statuses_path %>

bugtracker/app/views/ticket_statuses/index.html.erb
<h1>Listing ticket_statuses</h1>

<table>
  <tr>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ticket_statuses.each do |ticket_status| %>
  <tr>
    <td><%= ticket_status.status %></td>
    <td><%= link_to 'Show', ticket_status %></td>
    <td><%= link_to 'Edit', edit_ticket_status_path(ticket_status) %></td>
    <td><%= link_to 'Destroy', ticket_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket status', new_ticket_status_path %>

bugtracker/app/views/ticket_statuses/new.html.erb
<h1>New ticket_status</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_statuses_path %>

bugtracker/app/views/ticket_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @ticket_status.status %>
</p>


<%= link_to 'Edit', edit_ticket_status_path(@ticket_status) %> |
<%= link_to 'Back', ticket_statuses_path %>