bugtracker/config/routes.rb
Bugtracker::Application.routes.draw do
  get "search/do_search"

  resources :comments


  resources :ticket_statuses


  devise_for :users
  resources :tickets do
    resources :comments
  end
  resources :ticket_statuses
  resources  :projects do
    resources :tickets
  end
  resources :users

  root :to => "home#index"
  match '/token' => 'home#token', :as => :token
   
  match '/admin', :to =>'admin#index'
  match '/search', :to =>'search#index'
end

bugtracker/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  has_many :tickets, :dependent => :destroy
  validates :name, :length => { :in => 3..128 }
  self.per_page = 10
  
end

bugtracker/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    
    # @tickets = Ticket.all.select { |ticket| ticket.project == params[:id] }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
    
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def create_ticket
    puts "Attempted to create ticket"
  end
end

bugtracker/app/helpers/projects_helper.rb
module ProjectsHelper
end

bugtracker/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bugtracker/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |

bugtracker/app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class = "administrate">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

bugtracker/app/views/projects/new.html.erb
<h2>Create new project</h2>

<%= render 'form' %>

bugtracker/app/views/projects/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<b>Project Name:</b>
	<%= @project.name %>
</p>

<p>
	<b>Created on:</b>
	<%= @project.created_at %>
</p>

<table>
	<tr>
		<th>Title</th>
		<th>Reported by</th>
		<th>Project</th>
		<th>Status</th>
		<th>Assignee</th>
		<th>Created on:</th>
		<th>Last update on:</th>
	</tr>

	<% @project.tickets.page(params[:page]).each do |ticket| %>
	<tr>
		<td><%= link_to ticket.title, edit_ticket_path(ticket) %></td>
		<td><%= ticket.reported_by %></td>
		<td><%= ticket.project.name %></td>
		<td><%= ticket.status %></td>
		<td><%= User.find(ticket.assignee).name %></td>
		<td><%= ticket.created_at %></td>
		<td><%= ticket.updated_at %></td>
	</tr>
	<% end %>
</table>

<!-- <%= link_to 'Report a ticket', new_ticket_path %> -->
<%= link_to 'Edit', edit_project_path(@project) %>

<h2>Create a ticket:</h2>
<%= form_for([@project, @project.tickets.build]) do |f| %>
<div class="field">
	<%= f.label :title %>
	<br />
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :descritpion %>
	<br />
	<%= f.text_area :description %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

bugtracker/app/views/projects/show_admin.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>


<table>
  <tr>
    <th>User</th>
    <th>Project</th>
    <th>Status</th>
    <th>Assignee</th>
    <th>Timestamp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.user %></td>
    <td><%= ticket.project %></td>
    <td><%= ticket.status %></td>
    <td><%= ticket.assignee %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>